@startuml
skinparam linetype ortho

top to bottom direction

package "Drapit" {
  component Api {
    component Versions {
      [DTOs]
      [Controllers]
    }
  }

  component Global as G {
    [Global Decorators]
    [Event Bus]
    [Multilogger]
  }


  component Infrastructure {
    [Enums]
    [Event Managers] as EM
    [Loggers]
    [Repositories]
    [Web Server] as WS

    component "Open Api" as OA {
      [Generator]
      [Decorators]
    }
    [Startup]


    WS -[hidden]d-> OA
    WS -[hidden]up-> EM
  }

  component Application {
    [Domain]
    [Commands]
    [Queries]
    [Enums]
    [Interfaces]
    [Workers]
    [Listeners]
  }

  note top of G: This services are globally\navailable without the need\nto import them.

  Api --> Application
  Api --> Infrastructure
  Infrastructure --> Application
}

@enduml
